[server]
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false

[theme]
primaryColor = "#27AE60"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6" 
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[logger]
level = "error"